### ISSUE TITLE
Nothing happens on copying

### ISSUE THREAD

**Issue by vadimyer** [justone/remotecopy#6]
Hello!

I followed this guide (http://endot.org/2011/12/04/remotecopy-copy-from-remote-terminals-into-your-local-clipboard/) and all is working OK but in Vim nothing happens when I press <leader>y, just the standard message that text has been copied to clipboard, but it doesn't appear on my local machine.

I'm using Vim with vim-plug on remote Debian 8 machine, and the only thing I've added to my .vimrc was this line:

```
Plug 'justone/remotecopy'
```

Of course I've installed the plugin.

I've also tried to add a ~/.bash_aliases file with alias to remotecopy binary, and updated .vimrc accordingly:

```
let $BASH_ENV = "~/.bash_aliases"
```

Still no luck.

Can you provide some help?

**Comment by vadimyer** [comment]
OK, I've figured this out by copying autoload+plugin directories to the upper one directory and updating by `PlugUpdate`.

There are two left questions:

1) Can I "inject" the secret to my .vimrc file so I don't have to enter it even for the first time?
2) Can I get rid of that "press enter" on confirmation of my copy?

Thank you.

**Comment by justone** [comment]
Hello,

So sorry to not respond, I've been a bit busy for the last several months.

I'm glad you were able to get remotecopy to work.  You were right to move the vim files up, they're nested down a directory.  Now, for your questions:

1. I just added a new vimscript function that might be useful to you.  If you update and then create a file called `~.vim/after/plugin/remotecopy.vim` with the following contents, then the secret will be set from the beginning.:
```
call remotecopy#setsecret("rc-your-remotecopy-secret")
```
2. Do you get a "Press Enter" after every copy or just the first one?  I only get it on the first one.  If you don't want it to show up even then, just remove the two echo lines (the "Need to auth" and "Remote copied", the latter also needing the removal of the `else`).
3. I suppose you could make a function in your `.vimrc` that called the normal copy/paste bindings and then called the remotecopy ones.  I don't know the particulars of how this would work, but it seems feasible.

I hope this information helps.

**Comment by justone** [comment]
Oh, you can also make the setsecret call look like this:

```
call remotecopy#setsecret($RC_SECRET)
```

and then add `export RC_SECRET=rc-your-remotecopy-secret` to your shell config.
