### ISSUE TITLE
Directory structure needs minor modification to work with Vim Plug

### ISSUE THREAD

**Issue by owang** [justone/remotecopy#8]
In order for the plugin to load correctly for me, I had to change the structure such that `autoload` and `plugin` were in the root directory (rather than the `vim` subdirectory). Maybe there is another way? I don't know much about vim plugins.

**Comment by justone** [comment]
Hey @owang glad you are finding remotecopy useful. I just extracted the vim plugin to [its own repository](https://github.com/justone/remotecopy-vim). Let me know if that works for you.
