### ISSUE TITLE
From Mac to Mac, secret key not copied

### ISSUE THREAD

**Issue by owang** [justone/remotecopy#9]
When I ssh into a mac (from a Mac), the secret key does not seem to be copied. 

I can test the connection with 
```
telnet localhost 12345
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
HELLO 0.1
```

And it seems to be running, but running `remotecopy foo` prompts for the key and its not in the clipboard. 

When sshing to Linux it seems to work fine for me. Thanks!

**Comment by justone** [comment]
Thanks for reporting this issue, @owang. I'll have to dig up my mac to try and reproduce.

If you run the `remotecopyserver` in the foreground on your client mac, what is the output?

**Comment by owang** [comment]
Thanks! I do not get any output from `remotecopyserver` running in the foreground.

**Comment by justone** [comment]
Hm, that's odd.

I just tried it out from my mac to another mac and it worked fine.

Could you get the latest version from the repo? I just added a `--verbose` flag to `remotecopyserver` that should let us know what it sees. Please try the new version and let me know what it shows.

**Comment by owang** [comment]
Thanks! To my embarrassment, when I tried again this time with the verbose flag, everything worked fine, the secret key appeared in the clipboard and the server printed out a bunch of helpful messages.  I'll chock this one up to user error. Great tool by the way!

**Comment by justone** [comment]
Awesome. Glad it's working for you.
